In [1]:
import numpy as np

In [3]:
# Create a 1D NumPy array of numbers from 10 to 50.

arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
# Generate a 3x3 NumPy array with random integers between 1 and 100.
arr=np.random.randint(1,100,size=(3,3))
arr

array([[74, 59, 16],
       [55, 12,  3],
       [51, 85, 10]], dtype=int32)

In [5]:
# Create a 4x4 identity matrix using NumPy.
arr=np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
# Given an array [1,2,3,4,5,6,7,8,9], reshape it into a 3x3 matrix.
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Find the mean, median, and standard deviation of a NumPy array.
arr=np.arange(1,51)
print("Mean is ",arr.mean())
print("Median is ",np.median(arr))
print("Standard deviation is ",arr.std())

Mean is  25.5
Median is  25.5
Standard deviation is  14.430869689661812


In [13]:
# Create a NumPy array of 20 zeros, then replace the 5th element with 1.
arr=np.zeros(20)
arr[4]=1
arr


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [16]:
# Generate 10 random numbers between 0 and 1 and sort them.

my_arr=np.random.rand(10)
sorted_number=np.sort(my_arr)
sorted_number

array([0.22608173, 0.41674183, 0.43272262, 0.46936034, 0.47058461,
       0.5077336 , 0.53073775, 0.5821101 , 0.66951557, 0.90103132])

In [19]:
# Given an array [10, 20, 30, 40, 50], find the square root of each element.
arr=np.array([10,20,30,40,50])
sqr_arr=np.sqrt(arr)
sqr_arr

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [21]:
import numpy as np

matrix = np.arange(1, 26).reshape(5, 5)


corners = [matrix[0, 0],  
           matrix[0, -1],  
           matrix[-1, 0],  
           matrix[-1, -1]] 

print("Matrix:\n", matrix)
print("Corner elements:", corners)


Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Corner elements: [np.int64(1), np.int64(5), np.int64(21), np.int64(25)]
