In [2]:
import numpy as np


In [3]:
arr=np.array([1,2,3,4,5])
arr



array([1, 2, 3, 4, 5])

In [4]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr=np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
arr=np.random.randint(0,10,size=(3,3))
arr

array([[7, 2, 0],
       [6, 6, 1],
       [7, 2, 1]], dtype=int32)

In [ ]:
# Find the sum, mean, max, and min of the array [4, 7, 1, 9, 3].
my_arr=np.array([4,7,1,9,3])
arr_sum=my_arr.sum()
arr_mean=my_arr.mean()
arr_max=my_arr.max()
arr_min=my_arr.min()


np.int64(24)

In [21]:
arr_sum

np.int64(24)

In [22]:
arr_mean

np.float64(4.8)

In [23]:
arr_max

np.int64(9)

In [24]:
arr_min

np.int64(1)

In [25]:
arr=np.arange(1,50,5)
arr

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [27]:
# Reshape an array of numbers from 1–12 into a 3x4 matrix.
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr=np.array([10, 20, 30, 40, 50, 60, 70])
arr[2:5]

array([30, 40, 50])

In [29]:
# Generate a 5x5 identity matrix.
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Multiply two arrays:
A = [[1,2],[3,4]]
B = [[5,6],[7,8]]
arr1=np.array(A)
arr2=np.array(B)
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [32]:
# Create a 1D array of 100 random numbers between 0 and 1, then find:

# Mean

# Standard Deviation

# Variance
arr=np.random.rand(100)
arr.mean()


np.float64(0.5189361766602273)

In [33]:
arr.std()

np.float64(0.28856509953377496)

In [34]:
arr.var()

np.float64(0.08326981666893746)

In [35]:
# Generate a 10x10 matrix with values from 1 to 100, then:
arr=np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [36]:
arr[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [41]:
# Extract the 3x3 center block
arr[3:6,3:6]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56]])

In [43]:
# Create an array of shape (4,4) with random integers (1–20). Replace all values greater than 10 with -1.
arr=np.random.randint(1,21,size=(4,4))
arr[arr>10]=-1
arr

array([[ 3, -1,  2,  1],
       [-1, -1,  7,  9],
       [-1,  4, -1, -1],
       [-1, -1,  2,  3]], dtype=int32)

In [45]:
# Create two 3x3 matrices with random integers and find their dot product.
arr=np.random.randint(1,11,size=(3,3))
arr2=np.random.randint(1,11,size=(3,3))
np.dot(arr,arr2)

array([[ 31,  48,  37],
       [ 85, 114,  88],
       [152, 167, 136]], dtype=int32)

In [46]:
# Write a program that generates linearly spaced values between 0 and 5 (20 numbers), and then apply sin and cos 
# functions on them.
x=np.linspace(0,5,20)
np.sin(x)
np.cos(x)


array([ 1.        ,  0.96557333,  0.8646637 ,  0.70421909,  0.49528663,
        0.25225204, -0.00815095, -0.26799272, -0.5093823 , -0.7156992 ,
       -0.87273782, -0.96968552, -0.99986712, -0.96120454, -0.8563598 ,
       -0.69255183, -0.48105935, -0.23644432,  0.02445069,  0.28366219])