# MASTER PYTHON QUESTIONS

In [2]:
import numpy as np

In [3]:
# Q 1: Create a NumPy array from a Python list and perform
# basic operations like addition, multiplication, etc.

arr=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
add=arr+arr2
print("Additions",add)
multi=arr*arr2
print("Multiplications",multi)
print("Dot Product ",arr.dot(arr2))

Additions [11 22 33 44 55]
Multiplications [ 10  40  90 160 250]
Dot Product  550


In [4]:
# Q 2: Generate a NumPy array of random numbers and
# calculate its mean, median, and standard deviation.

arr=np.random.randint(1,21, size=(3,4))
print("Array:", arr)
print("Mean",arr.mean())
print("median",np.median(arr))
print("Standard Deviations",arr.std())

Array: [[17 15 15  2]
 [ 4  6 13 15]
 [17 11 14  4]]
Mean 11.083333333333334
median 13.5
Standard Deviations 5.298715777326511


In [5]:
# Q 3: Create a NumPy array and reshape it into a different
# shape.

arr=np.arange(1,13)
print(arr.reshape(3,4))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:

arr3=np.arange(1,31)
print(arr3.reshape(6,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [7]:
arr4=np.arange(1,51)
print(arr4.reshape(10,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [8]:
# 2+ Given a list of numbers, create a NumPy array and find
# the sum and product of its elements/

arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Sum ",sum(arr))
print("Product",np.prod(arr))

Sum  55
Product 3628800


In [9]:
# + Implement a program that generates a NumPy array with
# numbers from 0 to 9 and reshapes it into a 3x3 matrix/
arr=np.arange(1,10)
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Write a Python program that uses NumPy to find the
# mean, median, and standard deviation of a dataset.



In [11]:
#  Create a function that takes a list of numbers and returns
# the NumPy array sorted in ascending order
def sort_array(num_list):
    arr=np.array(num_list)
    return np.sort(arr)

print(sort_array([5,2,9,1,5,6]))  

[1 2 5 5 6 9]


In [12]:
#  Given a list of lists, create a 2D NumPy array and find the
# sum of elements in each row and column
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(list_of_lists)
print("Sum Of Each Row",arr.sum(axis=1))
print("Sum of Each Column",arr.sum(axis=0))

Sum Of Each Row [ 6 15 24]
Sum of Each Column [12 15 18]


In [19]:
# Implement a program that generates a random NumPy
# array and finds the maximum and minimum values
random_arr=np.random.randint(1,100,size=(4,5))
print(random_arr)
print("Maximum value",random_arr.max())
print("Minimum Value",random_arr.min())


[[76 71 67 54 44]
 [49 64  2 28 42]
 [29 99 60 59  8]
 [84 52  5 15 54]]
Maximum value 99
Minimum Value 2


In [24]:
# Write a function that takes a NumPy array and returns a
# new array with all elements squared
def squared_ele(num):
    arr=np.array(num)
    return arr**2
print(squared_ele([5,3,2,6]))


[25  9  4 36]


In [15]:
#Given a NumPy array, calculate the dot product of the
# array with itself
arr=np.array([1,2,3,4])
print(np.prod(arr))



24


In [16]:
# Create a program that uses NumPy to calculate the
# inverse of a 2x2 matrix
import numpy as np


mat = np.array([[4, 7],
                [2, 6]])

# Calculate inverse
inv_mat = np.linalg.inv(mat)

print("Original Matrix:\n", mat)
print("\nInverse Matrix:\n", inv_mat)


Original Matrix:
 [[4 7]
 [2 6]]

Inverse Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [17]:
#  Implement a function that takes a NumPy array and
# returns the transpose of the array.

import numpy as np

def transpose_matrix(arr):
    return arr.T   

mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Matrix:\n", mat)
print("\nTranspose Matrix:\n", transpose_matrix(mat))


Original Matrix:
 [[1 2 3]
 [4 5 6]]

Transpose Matrix:
 [[1 4]
 [2 5]
 [3 6]]
