# Introductions

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr=np.arange(1,21,2) #start,stop,step
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
arr=np.zeros((3,4)) #3 rows and 4 columns
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# linspace → average gaps banata hai.
# 🔹 linspace (average jaisa kaam karta hai)

# Ye average spacing calculate karta hai.

# Matlab start aur stop ke darmiyan jitne numbers aap maango, unko equal gap se arrange karega.

# Isko hum “average gap” bhi keh sakte hain.

arr=np.linspace(0,10,5) #start,stop,numbers
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
# Value in normalization of data 1 to 10
np.random.rand(10)

array([0.76366104, 0.85718238, 0.40000781, 0.02946125, 0.57767134,
       0.93544782, 0.18670921, 0.12002559, 0.89326969, 0.36351635])

In [ ]:
# value in standard normal distribution 3 to -3
np.random.randn(10)

array([ 0.53082982,  0.82789483,  1.42983051, -0.04736057, -1.31303413,
        0.82885521,  0.89757693, -0.57810536, -0.1713466 ,  0.95537366])

In [14]:
np.random.randint(1,100,10) #start,stop,numbers


array([65, 78, 65, 58, 37, 49, 68, 86, 86, 24], dtype=int32)

# Attribute

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape#3 rows and 3 columns


(3, 3)

In [19]:
arr.ndim #dimension

2

In [20]:
arr.dtype #data type

dtype('int64')

# ARRAY METHODS

In [21]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.min()

np.int64(1)

In [24]:
arr.sum()

np.int64(45)

In [27]:
# agar column chaie tu 0 
# or agr row chie tu 1
arr.sum(axis=0) #column wise sum


array([12, 15, 18])

In [28]:
arr.sum(axis=1) #row wise sum

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
# jo bari value hai uska index batata hai
arr.argmax()

np.int64(8)

In [32]:
arr.argmin()

np.int64(0)

# Reshaping and Resizing

In [33]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr=arr.reshape(6,5) #6 rows and 5 columns
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Numpy indexing and Slicing

In [39]:
arr=np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
arr[1:5]

array([12, 13, 14, 15])

In [41]:
arr[3::2] #3rd index se start kar ke 2 step ke bad print karay ga

array([14, 16, 18, 20])